# Advanced NumPy

In [2]:
from __future__ import division
from numpy.random import randn
from pandas import Series
import numpy as np
np.set_printoptions(precision=4)
import sys; #sys.path.append('book_scripts')
#%cd book_scripts

## ndarray object internals

### NumPy dtype hierarchy

In [2]:
ints = np.ones(10, dtype=np.uint16)
floats = np.ones(10, dtype=np.float32)
np.issubdtype(ints.dtype, np.integer)
np.issubdtype(floats.dtype, np.floating)

True

In [3]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

## Advanced array manipulation

### Reshaping arrays

In [4]:
arr = np.arange(8)
arr
arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [5]:
arr.reshape((4, 2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [6]:
arr = np.arange(15)
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [7]:
other_arr = np.ones((3, 5))
other_arr.shape
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
arr = np.arange(15).reshape((5, 3))
arr
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### C vs. Fortran order

In [10]:
arr = np.arange(12).reshape((3, 4))
arr
arr.ravel()
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

### Concatenating and splitting arrays

In [13]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [15]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [16]:
from numpy.random import randn
arr = randn(5, 2)
arr
first, second, third = np.split(arr, [1, 3])
first
second
third

array([[ 1.2975, -0.9942],
       [ 0.6705,  0.3311]])

#### Stacking helpers: 

In [ ]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = randn(3, 2)
np.r_[arr1, arr2]
np.c_[np.r_[arr1, arr2], arr]

In [ ]:
np.c_[1:6, -10:-5]

### Repeating elements: tile and repeat

In [ ]:
arr = np.arange(3)
arr.repeat(3)

In [ ]:
arr.repeat([2, 3, 4])

In [ ]:
arr = randn(2, 2)
arr
arr.repeat(2, axis=0)

In [ ]:
arr.repeat([2, 3], axis=0)
arr.repeat([2, 3], axis=1)

In [ ]:
arr
np.tile(arr, 2)

In [ ]:
arr
np.tile(arr, (2, 1))
np.tile(arr, (3, 2))

### Fancy indexing equivalents: take and put

In [18]:
arr = np.arange(10) * 100
inds = [7, 1, 2, 6]
arr[inds]

array([700, 100, 200, 600])

### arr.take(inds)
arr.put(inds, 42)
arr
arr.put(inds, [40, 41, 42, 43])
arr

In [ ]:
inds = [2, 0, 2, 1]
arr = randn(2, 4)
arr
arr.take(inds, axis=1)

### take/put vs fancy indexing

In [19]:
arr = randn(1000, 50)

In [20]:
inds = np.random.permutation(1000)[:500]

In [21]:
%timeit arr[inds]

The slowest run took 41.49 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 18.2 µs per loop


In [22]:
%timeit arr.take(inds, axis=0)

The slowest run took 4.45 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 19.8 µs per loop


## Broadcasting

In [2]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [3]:
arr * 4

array([ 0,  4,  8, 12, 16])

Column mean handling

In [5]:
arr = randn(4, 3)
arr

array([[-0.175 , -1.554 ,  1.2457],
       [-1.453 ,  0.5243, -0.3732],
       [ 0.3627,  0.7066,  0.1387],
       [ 0.1304,  1.2416,  1.1571]])

In [6]:
arr.mean(0)

array([-0.2837,  0.2296,  0.5421])

In [7]:
demeaned = arr - arr.mean(0)
demeaned

array([[ 0.1087, -1.7836,  0.7037],
       [-1.1693,  0.2947, -0.9153],
       [ 0.6464,  0.477 , -0.4034],
       [ 0.4142,  1.012 ,  0.615 ]])

In [8]:
demeaned.mean(0)

array([ -2.7756e-17,   5.5511e-17,   5.5511e-17])

In [11]:
arr - [1, 2, 3]

array([[-1.175 , -3.554 , -1.7543],
       [-2.453 , -1.4757, -3.3732],
       [-0.6373, -1.2934, -2.8613],
       [-0.8696, -0.7584, -1.8429]])

Row mean handling

In [12]:
arr

array([[-0.175 , -1.554 ,  1.2457],
       [-1.453 ,  0.5243, -0.3732],
       [ 0.3627,  0.7066,  0.1387],
       [ 0.1304,  1.2416,  1.1571]])

In [14]:
row_means = arr.mean(1)
row_means

array([-0.1611, -0.434 ,  0.4027,  0.843 ])

In [15]:
row_means.reshape((4, 1))

array([[-0.1611],
       [-0.434 ],
       [ 0.4027],
       [ 0.843 ]])

In [18]:
demeaned = arr - row_means.reshape((4, 1))
demeaned

array([[-0.0139, -1.3929,  1.4068],
       [-1.019 ,  0.9583,  0.0608],
       [-0.04  ,  0.3039, -0.264 ],
       [-0.7126,  0.3985,  0.314 ]])

In [19]:
demeaned.mean(1)

array([  0.0000e+00,   1.8504e-17,  -3.7007e-17,  -3.7007e-17])

### Broadcasting over other axes

In [20]:
arr - arr.mean(1)

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [21]:
arr - arr.mean(1).reshape((4, 1))

array([[-0.0139, -1.3929,  1.4068],
       [-1.019 ,  0.9583,  0.0608],
       [-0.04  ,  0.3039, -0.264 ],
       [-0.7126,  0.3985,  0.314 ]])

In [22]:
arr = np.zeros((4, 4))
arr

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [23]:
arr_3d = arr[:, np.newaxis, :]
arr_3d

array([[[ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.]]])

In [24]:
arr_3d.shape

(4, 1, 4)

In [25]:
arr_1d = np.random.normal(size=3)
arr_1d

array([ 1.3852,  1.1428,  0.9184])

In [26]:
arr_1d[:, np.newaxis]

array([[ 1.3852],
       [ 1.1428],
       [ 0.9184]])

In [27]:
arr_1d[np.newaxis, :]

array([[ 1.3852,  1.1428,  0.9184]])

In [28]:
arr = randn(3, 4, 5)
arr

array([[[ 1.5555,  0.3623, -2.5111, -1.5041,  0.1651],
        [ 2.3175,  0.4963, -0.9817, -1.5293, -1.5142],
        [-0.0688, -2.9793, -0.8068,  0.6971, -0.3819],
        [ 0.0306, -0.3101, -1.7023,  0.8447, -0.6407]],

       [[-0.7871, -0.1414, -0.4508, -0.7525, -0.5579],
        [ 1.6422, -0.4445, -2.9722,  0.9091,  0.8221],
        [ 0.3626, -2.1828,  0.4228, -1.376 , -1.9457],
        [ 0.1721, -1.4372,  1.473 , -0.2002,  1.1362]],

       [[-0.3178, -0.6356, -0.7427, -0.8118,  1.3718],
        [ 1.3922, -0.0246, -0.4286,  0.5298, -0.2346],
        [ 0.6914, -0.6513,  0.7415, -0.2068, -1.3067],
        [-0.0684,  0.934 , -0.7535, -0.0781, -1.0159]]])

In [29]:
depth_means = arr.mean(2)
depth_means

array([[-0.3865, -0.2423, -0.7079, -0.3556],
       [-0.5379, -0.0087, -0.9438,  0.2288],
       [-0.2272,  0.2468, -0.1464, -0.1964]])

In [30]:
depth_means[:, :, np.newaxis]

array([[[-0.3865],
        [-0.2423],
        [-0.7079],
        [-0.3556]],

       [[-0.5379],
        [-0.0087],
        [-0.9438],
        [ 0.2288]],

       [[-0.2272],
        [ 0.2468],
        [-0.1464],
        [-0.1964]]])

In [32]:
demeaned = arr - depth_means[:, :, np.newaxis]
demeaned

array([[[ 1.9419,  0.7488, -2.1247, -1.1176,  0.5515],
        [ 2.5597,  0.7386, -0.7394, -1.287 , -1.2719],
        [ 0.6392, -2.2714, -0.0989,  1.405 ,  0.326 ],
        [ 0.3862,  0.0454, -1.3467,  1.2003, -0.2852]],

       [[-0.2491,  0.3966,  0.0871, -0.2146, -0.02  ],
        [ 1.6509, -0.4358, -2.9635,  0.9177,  0.8307],
        [ 1.3064, -1.239 ,  1.3667, -0.4322, -1.0019],
        [-0.0566, -1.666 ,  1.2442, -0.429 ,  0.9074]],

       [[-0.0906, -0.4083, -0.5155, -0.5846,  1.599 ],
        [ 1.1453, -0.2714, -0.6754,  0.2829, -0.4814],
        [ 0.8378, -0.5049,  0.8879, -0.0604, -1.1603],
        [ 0.128 ,  1.1304, -0.5571,  0.1183, -0.8195]]])

In [33]:
demeaned.mean(2)

array([[  2.2204e-17,  -4.4409e-17,  -7.7716e-17,  -6.6613e-17],
       [  0.0000e+00,   4.4409e-17,  -1.3323e-16,   0.0000e+00],
       [  8.8818e-17,  -3.3307e-17,  -4.4409e-17,  -2.2204e-17]])

In [ ]:
def demean_axis(arr, axis=0):
    means = arr.mean(axis)

    # This generalized things like [:, :, np.newaxis] to N dimensions
    indexer = [slice(None)] * arr.ndim
    indexer[axis] = np.newaxis
    return arr - means[indexer]

### Setting array values by broadcasting

In [34]:
arr = np.zeros((4, 3))
arr[:] = 5
arr

array([[ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.]])

In [37]:
col = np.array([1.28, -0.42, 0.44, 1.6])
col

array([ 1.28, -0.42,  0.44,  1.6 ])

In [36]:
col[:, np.newaxis]

array([[ 1.28],
       [-0.42],
       [ 0.44],
       [ 1.6 ]])

In [40]:
col[np.newaxis, :]

array([[ 1.28, -0.42,  0.44,  1.6 ]])

In [41]:
arr[:] = col[:, np.newaxis]
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [42]:
arr[:2] = [[-1.37], [0.509]]
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

## Advanced ufunc usage

### Ufunc instance methods

In [46]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.add.reduce(arr)

45

In [48]:
arr.sum()

45

In [49]:
np.random.seed(12346)

In [53]:
arr = randn(5, 5)
arr

array([[  5.2242e-01,   1.0642e-01,   1.0271e-01,  -1.0823e-01,
          5.4860e-02],
       [  1.9637e-01,  -1.9387e-01,  -1.4566e+00,   8.5745e-01,
         -7.4158e-01],
       [ -7.8036e-01,  -1.0642e-01,   5.9371e-01,  -1.2835e+00,
          4.7796e-01],
       [  1.2924e+00,   1.5165e-01,  -1.4663e+00,  -1.4334e+00,
         -9.7753e-02],
       [  1.2351e+00,   1.3551e-01,  -7.0550e-04,   2.5360e-01,
         -1.8325e-01]])

In [55]:
arr[::2].sort(1) # sort a few rows
arr

array([[ -1.0823e-01,   5.4860e-02,   1.0271e-01,   1.0642e-01,
          5.2242e-01],
       [  1.9637e-01,  -1.9387e-01,  -1.4566e+00,   8.5745e-01,
         -7.4158e-01],
       [ -1.2835e+00,  -7.8036e-01,  -1.0642e-01,   4.7796e-01,
          5.9371e-01],
       [  1.2924e+00,   1.5165e-01,  -1.4663e+00,  -1.4334e+00,
         -9.7753e-02],
       [ -1.8325e-01,  -7.0550e-04,   1.3551e-01,   2.5360e-01,
          1.2351e+00]])

In [59]:
arr[:, :-1]

array([[ -1.0823e-01,   5.4860e-02,   1.0271e-01,   1.0642e-01],
       [  1.9637e-01,  -1.9387e-01,  -1.4566e+00,   8.5745e-01],
       [ -1.2835e+00,  -7.8036e-01,  -1.0642e-01,   4.7796e-01],
       [  1.2924e+00,   1.5165e-01,  -1.4663e+00,  -1.4334e+00],
       [ -1.8325e-01,  -7.0550e-04,   1.3551e-01,   2.5360e-01]])

In [57]:
arr[:, 1:]

array([[  5.4860e-02,   1.0271e-01,   1.0642e-01,   5.2242e-01],
       [ -1.9387e-01,  -1.4566e+00,   8.5745e-01,  -7.4158e-01],
       [ -7.8036e-01,  -1.0642e-01,   4.7796e-01,   5.9371e-01],
       [  1.5165e-01,  -1.4663e+00,  -1.4334e+00,  -9.7753e-02],
       [ -7.0550e-04,   1.3551e-01,   2.5360e-01,   1.2351e+00]])

In [60]:
arr[:, :-1] < arr[:, 1:]

array([[ True,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [61]:
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1)

array([ True, False,  True, False,  True], dtype=bool)

In [62]:
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=0)

array([False, False,  True, False], dtype=bool)

In [63]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [64]:
np.add.accumulate(arr, axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [65]:
np.add.accumulate(arr, axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  7,  9, 11, 13],
       [15, 18, 21, 24, 27]])

In [66]:
arr = np.arange(3).repeat([1, 2, 2])
arr

array([0, 1, 1, 2, 2])

In [67]:
np.multiply.outer(arr, np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [68]:
result = np.subtract.outer(randn(3, 4), randn(5))
result

array([[[-1.2458, -1.9973, -1.5742, -1.118 , -1.1526],
        [-0.1124, -0.8639, -0.4409,  0.0154, -0.0192],
        [-0.8168, -1.5683, -1.1452, -0.6889, -0.7235],
        [-1.3675, -2.119 , -1.6959, -1.2396, -1.2742]],

       [[-3.302 , -4.0535, -3.6305, -3.1742, -3.2088],
        [ 0.4443, -0.3072,  0.1159,  0.5722,  0.5376],
        [-0.1014, -0.853 , -0.4299,  0.0264, -0.0082],
        [-1.3888, -2.1403, -1.7172, -1.2609, -1.2955]],

       [[ 0.1796, -0.5719, -0.1489,  0.3074,  0.2728],
        [ 0.1937, -0.5578, -0.1347,  0.3216,  0.287 ],
        [-0.0345, -0.786 , -0.3629,  0.0934,  0.0588],
        [-1.3284, -2.08  , -1.6569, -1.2006, -1.2352]]])

In [69]:
result.shape

(3, 4, 5)

In [70]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
np.add.reduceat(arr, [0, 5, 8])

array([10, 18, 17])

In [72]:
arr = np.multiply.outer(np.arange(4), np.arange(5))
arr

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [73]:
np.add.reduceat(arr, [0, 2, 4], axis=1)

array([[ 0,  0,  0],
       [ 1,  5,  4],
       [ 2, 10,  8],
       [ 3, 15, 12]])

### Custom ufuncs

In [76]:
def add_elements(x, y):
    return x - y
add_them = np.frompyfunc(add_elements, 2, 1)
add_them(np.arange(8), np.arange(8)*2)

array([0, -1, -2, -3, -4, -5, -6, -7], dtype=object)

In [77]:
add_them = np.vectorize(add_elements, otypes=[np.float64])
add_them(np.arange(8), np.arange(8))

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [79]:
arr = randn(10000)
%timeit add_them(arr, arr)

100 loops, best of 3: 2.01 ms per loop


In [80]:
%timeit np.add(arr, arr)

The slowest run took 45.38 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 4.06 µs per loop


## Structured and record arrays

In [81]:
dtype = [('x', np.float64), ('y', np.int32)]
sarr = np.array([(1.5, 6), (np.pi, -2)], dtype=dtype)
sarr

array([(1.5, 6), (3.141592653589793, -2)], 
      dtype=[('x', '<f8'), ('y', '<i4')])

In [82]:
sarr[0]

(1.5, 6)

In [83]:
sarr[0]['y']

6

In [84]:
sarr['x']

array([ 1.5   ,  3.1416])

### Nested dtypes and multidimensional fields

In [85]:
dtype = [('x', np.int64, 3), ('y', np.int32)]
arr = np.zeros(4, dtype=dtype)
arr

array([([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0)], 
      dtype=[('x', '<i8', (3,)), ('y', '<i4')])

In [86]:
arr[0]['x']

array([0, 0, 0])

In [87]:
arr['x']

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [88]:
dtype = [('x', [('a', 'f8'), ('b', 'f4')]), ('y', np.int32)]
data = np.array([((1, 2), 5), ((3, 4), 6)], dtype=dtype)
data

array([((1.0, 2.0), 5), ((3.0, 4.0), 6)], 
      dtype=[('x', [('a', '<f8'), ('b', '<f4')]), ('y', '<i4')])

In [89]:
data['x']

array([(1.0, 2.0), (3.0, 4.0)], 
      dtype=[('a', '<f8'), ('b', '<f4')])

In [90]:
data['y']

array([5, 6], dtype=int32)

In [91]:
data['x']['a']

array([ 1.,  3.])

### Why use structured arrays?

### Structured array manipulations: numpy.lib.recfunctions

## More about sorting

In [92]:
arr = randn(6)
arr

array([ 0.4795,  0.0288, -0.1513, -0.2368,  0.61  , -0.385 ])

In [93]:
arr.sort()
arr

array([-0.385 , -0.2368, -0.1513,  0.0288,  0.4795,  0.61  ])

In [96]:
arr = randn(3, 5)
arr

array([[-0.8176, -0.1002, -0.5929,  1.2256,  1.0202],
       [ 0.5133, -0.7435, -0.1507,  0.2622, -2.7999],
       [-1.3688, -0.9731,  0.2897, -1.5799, -1.1343]])

In [97]:
arr[:, 0].sort()  # Sort first column values in-place
arr

array([[-1.3688, -0.1002, -0.5929,  1.2256,  1.0202],
       [-0.8176, -0.7435, -0.1507,  0.2622, -2.7999],
       [ 0.5133, -0.9731,  0.2897, -1.5799, -1.1343]])

In [98]:
arr = randn(5)
arr

array([-0.5734, -0.4247, -1.3484, -0.7371, -0.5543])

In [100]:
np.sort(arr)

array([-1.3484, -0.7371, -0.5734, -0.5543, -0.4247])

In [101]:
arr

array([-0.5734, -0.4247, -1.3484, -0.7371, -0.5543])

In [102]:
arr = randn(3, 5)
arr

array([[-1.1869,  1.9229,  0.6173, -0.4207, -0.8286],
       [-1.1959, -0.2837, -1.1584,  0.8378,  0.7781],
       [-0.9529,  1.5012,  1.1616, -1.5151,  0.5283]])

In [103]:
arr.sort(axis=1)

In [104]:
arr

array([[-1.1869, -0.8286, -0.4207,  0.6173,  1.9229],
       [-1.1959, -1.1584, -0.2837,  0.7781,  0.8378],
       [-1.5151, -0.9529,  0.5283,  1.1616,  1.5012]])

In [105]:
arr[:, ::-1]

array([[ 1.9229,  0.6173, -0.4207, -0.8286, -1.1869],
       [ 0.8378,  0.7781, -0.2837, -1.1584, -1.1959],
       [ 1.5012,  1.1616,  0.5283, -0.9529, -1.5151]])

### Indirect sorts: argsort and lexsort

argsort

In [4]:
values = np.array([5, 0, 1, 3, 2])
values

array([5, 0, 1, 3, 2])

In [5]:
indexer = values.argsort()
indexer

array([1, 2, 4, 3, 0])

In [6]:
values[indexer]

array([0, 1, 2, 3, 5])

argsort on 2-dimentional array

In [7]:
arr = randn(3, 5)
arr

array([[-0.0212,  0.0886, -0.0103,  0.669 ,  1.6723],
       [ 0.8503, -0.624 , -2.2556, -0.2805, -0.958 ],
       [ 1.4282,  0.4144,  1.9128, -0.6768,  0.1454]])

In [8]:
arr[0] = values
arr

array([[ 5.    ,  0.    ,  1.    ,  3.    ,  2.    ],
       [ 0.8503, -0.624 , -2.2556, -0.2805, -0.958 ],
       [ 1.4282,  0.4144,  1.9128, -0.6768,  0.1454]])

In [9]:
arr[:, arr[0].argsort()]

array([[ 0.    ,  1.    ,  2.    ,  3.    ,  5.    ],
       [-0.624 , -2.2556, -0.958 , -0.2805,  0.8503],
       [ 0.4144,  1.9128,  0.1454, -0.6768,  1.4282]])

lexsort

In [10]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
first_name

array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'], 
      dtype='<U7')

In [11]:
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])
last_name

array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'], 
      dtype='<U7')

In [15]:
# second parameter (last_name) is first sort item
sorter = np.lexsort((first_name, last_name))
sorter

array([1, 2, 3, 0, 4])

In [18]:
zip(last_name[sorter], first_name[sorter])

### Alternate sort algorithms

In [19]:
values = np.array(['2:first', '2:second', '1:first', '1:second', '1:third'])
values

array(['2:first', '2:second', '1:first', '1:second', '1:third'], 
      dtype='<U8')

In [20]:
key = np.array([2, 2, 1, 1, 1])
key

array([2, 2, 1, 1, 1])

In [21]:
indexer = key.argsort(kind='mergesort')
indexer

array([2, 3, 4, 0, 1])

In [22]:
values.take(indexer)

array(['1:first', '1:second', '1:third', '2:first', '2:second'], 
      dtype='<U8')

In [23]:
indexer = key.argsort(kind='quicksort')
indexer

array([2, 3, 4, 0, 1])

### numpy.searchsorted: Finding elements in a sorted array

In [24]:
arr = np.array([0, 1, 7, 12, 15])
arr.searchsorted(9)

3

In [25]:
arr.searchsorted([0, 8, 11, 16])

array([0, 3, 3, 5])

In [26]:
arr = np.array([0, 0, 0, 1, 1, 1, 1])
arr.searchsorted([0, 1])

array([0, 3])

In [27]:
arr.searchsorted([0, 1], side='right')

array([3, 7])

In [28]:
data = np.floor(np.random.uniform(0, 10000, size=50))
data

array([ 7080.,  8961.,  5324.,  5008.,  4512.,  9226.,  6248.,  7973.,
        6094.,  2410.,  9744.,    27.,  7654.,  6940.,  3598.,  9600.,
         443.,  2525.,  5727.,  9598.,  4142.,  1798.,  4669.,  5876.,
        7552.,  2633.,  1195.,  6300.,  6746.,  1749.,   721.,  5557.,
        6060.,  7231.,  3899.,  2263.,  9322.,  2934.,  8486.,  6268.,
        8756.,  1776.,  1923.,  5927.,  2356.,  4199.,   273.,  7320.,
        7673.,  9784.])

In [30]:
bins = np.array([0, 100, 1000, 5000, 10000])
bins

array([    0,   100,  1000,  5000, 10000])

In [31]:
labels = bins.searchsorted(data)
labels

array([4, 4, 4, 4, 3, 4, 4, 4, 4, 3, 4, 1, 4, 4, 3, 4, 2, 3, 4, 4, 3, 3, 3,
       4, 4, 3, 3, 4, 4, 3, 2, 4, 4, 4, 3, 3, 4, 3, 4, 4, 4, 3, 3, 4, 3, 3,
       2, 4, 4, 4])

In [32]:
Series(data).groupby(labels).mean()

1      27.000000
2     479.000000
3    2857.705882
4    7380.517241
dtype: float64

In [33]:
np.digitize(data, bins)

array([4, 4, 4, 4, 3, 4, 4, 4, 4, 3, 4, 1, 4, 4, 3, 4, 2, 3, 4, 4, 3, 3, 3,
       4, 4, 3, 3, 4, 4, 3, 2, 4, 4, 4, 3, 3, 4, 3, 4, 4, 4, 3, 3, 4, 3, 3,
       2, 4, 4, 4])

## NumPy matrix class

In [46]:
X =  np.array([[ 8.82768214,  3.82222409, -1.14276475,  2.04411587],
               [ 3.82222409,  6.75272284,  0.83909108,  2.08293758],
               [-1.14276475,  0.83909108,  5.01690521,  0.79573241],
               [ 2.04411587,  2.08293758,  0.79573241,  6.24095859]])
X[:, 0]  # one-dimensional

array([ 8.8277,  3.8222, -1.1428,  2.0441])

In [47]:
y = X[:, :1]  # two-dimensional by slicing
y

array([[ 8.8277],
       [ 3.8222],
       [-1.1428],
       [ 2.0441]])

In [37]:
np.dot(y.T, np.dot(X, y))

array([[ 1195.468]])

using np.matrix

In [38]:
Xm = np.matrix(X)
Xm

matrix([[ 8.8277,  3.8222, -1.1428,  2.0441],
        [ 3.8222,  6.7527,  0.8391,  2.0829],
        [-1.1428,  0.8391,  5.0169,  0.7957],
        [ 2.0441,  2.0829,  0.7957,  6.241 ]])

In [48]:
ym = Xm[:, 0]
ym

matrix([[ 8.8277],
        [ 3.8222],
        [-1.1428],
        [ 2.0441]])

In [49]:
ym.T * Xm * ym

matrix([[ 1195.468]])

In [50]:
Xm.I * X

matrix([[  1.0000e+00,   6.9616e-17,  -4.0136e-17,   8.1258e-17],
        [ -2.3716e-17,   1.0000e+00,   2.2230e-17,  -2.5721e-17],
        [  1.0957e-16,   5.0783e-18,   1.0000e+00,   7.8658e-18],
        [ -5.7092e-17,  -3.7777e-18,   6.2391e-18,   1.0000e+00]])

## Advanced array input and output

### Memory-mapped files

In [51]:
mmap = np.memmap('mymmap', dtype='float64', mode='w+', shape=(10000, 10000))
mmap

memmap([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [54]:
section = mmap[:5]
section

memmap([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [55]:
section[:] = np.random.randn(5, 10000)
section

memmap([[-0.6046, -0.5508,  0.4682, ...,  1.0207,  0.24  , -1.2797],
       [-0.0316,  1.9272,  1.9507, ..., -1.2374,  0.1428,  2.0128],
       [ 1.7958, -0.2634, -0.325 , ..., -1.2108,  0.771 ,  0.7693],
       [-0.5077, -0.4308, -0.4809, ...,  0.7332,  0.3593,  1.5983],
       [ 0.3068,  1.3228,  0.1498, ..., -0.1324,  1.6794, -0.5274]])

In [58]:
mmap.flush()
mmap

NameError: name 'mmap' is not defined

In [57]:
del mmap

In [59]:
mmap = np.memmap('mymmap', dtype='float64', shape=(10000, 10000))
mmap

memmap([[-0.6046, -0.5508,  0.4682, ...,  1.0207,  0.24  , -1.2797],
       [-0.0316,  1.9272,  1.9507, ..., -1.2374,  0.1428,  2.0128],
       [ 1.7958, -0.2634, -0.325 , ..., -1.2108,  0.771 ,  0.7693],
       ..., 
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ]])

In [60]:
%xdel mmap
!rm mymmap

### HDF5 and other array storage options

## Performance tips

### The importance of contiguous memory

In [61]:
arr_c = np.ones((1000, 1000), order='C')
arr_c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [62]:
arr_f = np.ones((1000, 1000), order='F')
arr_f.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [63]:
arr_f.flags.f_contiguous

True

In [64]:
%timeit arr_c.sum(1)

1000 loops, best of 3: 351 µs per loop


In [65]:
%timeit arr_f.sum(1)

1000 loops, best of 3: 361 µs per loop


In [66]:
arr_f.copy('C').flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [67]:
arr_c[:50].flags.contiguous
arr_c[:, :50].flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [68]:
%xdel arr_c
%xdel arr_f
#%cd ..

## Other speed options: Cython, f2py, C

```cython
from numpy cimport ndarray, float64_t

def sum_elements(ndarray[float64_t] arr):
    cdef Py_ssize_t i, n = len(arr)
    cdef float64_t result = 0

    for i in range(n):
        result += arr[i]

    return result
```